-- Execute este arquivo no SQL Editor do Supabase.

create table if not exists public.tendencia_notas (
  id bigint generated by default as identity primary key,
  data date not null unique,
  amarela integer not null default 0 check (amarela >= 0),
  vermelha integer not null default 0 check (vermelha >= 0),
  nd integer not null default 0 check (nd >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.tendencia_notas enable row level security;
alter table public.admin_users enable row level security;

-- Função usada pelas políticas sem expor a tabela admin_users ao navegador.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users a
    where a.user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- Leitura pública do gráfico.
drop policy if exists "Leitura publica tendencia" on public.tendencia_notas;
create policy "Leitura publica tendencia"
on public.tendencia_notas
for select
to anon, authenticated
using (true);

-- Escrita apenas para administradores autenticados.
drop policy if exists "Admin insere tendencia" on public.tendencia_notas;
create policy "Admin insere tendencia"
on public.tendencia_notas
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admin atualiza tendencia" on public.tendencia_notas;
create policy "Admin atualiza tendencia"
on public.tendencia_notas
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admin exclui tendencia" on public.tendencia_notas;
create policy "Admin exclui tendencia"
on public.tendencia_notas
for delete
to authenticated
using (public.is_admin());

-- Mantém updated_at automaticamente.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tendencia_notas_updated_at on public.tendencia_notas;
create trigger tendencia_notas_updated_at
before update on public.tendencia_notas
for each row execute function public.set_updated_at();

-- Dados iniciais equivalentes ao HTML original.
insert into public.tendencia_notas (data, amarela, vermelha, nd)
values
  ('1990-01-12', 45, 78, 181),
  ('1990-02-12', 78, 20, 104)
on conflict (data) do nothing;

-- Depois de criar o usuário em Authentication > Users, transforme-o em admin:
-- 1) copie o UUID do usuário
-- 2) execute, substituindo o UUID:
-- insert into public.admin_users (user_id) values ('COLE-O-UUID-AQUI');
